version: '3.4'

services:
  kingstoninc:
    image: kingstoninc
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
